#!/bin/bash
#
# alfresco      Startup script for Alfresco
#
# chkconfig: 345 96 14
# description: Starts up the Alfresco ECM engine
# processname: alfresco
# pidfile: $ALF_HOME/alfresco.pid
#

# User under which tomcat will run
ALF_HOME=/data/alfresco-5.0.2.5
ALF_SCRIPT=$ALF_HOME/alfresco.sh
JAVA_HOME=$ALF_HOME/java

RETVAL=0

# start, debug, stop, and status functions
start() {
    # Start Tomcat in normal mode
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
    export JAVA_HOME=$JAVA_HOME
    if [ $SHUTDOWN_PORT -ne 0 ]; then
        echo "Alfresco already started"
    else
        echo "Starting alfresco..."
        su - alfresco -c "$ALF_SCRIPT start"
        SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        while [ $SHUTDOWN_PORT -eq 0 ]; do
            sleep 1
            SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        done
        RETVAL=$?
        echo "Alfresco started"
        [ $RETVAL=0 ] && touch /var/lock/subsys/alfresco
    fi
}

stop() {
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
    export JAVA_HOME=$JAVA_HOME
    if [ $SHUTDOWN_PORT -eq 0 ]; then
        echo "Alfresco already stopped"
    else
        echo "Stopping alfresco..."
        su - alfresco -c "$ALF_SCRIPT stop"
        SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        RETVAL=$?
        echo "Alfresco stopped"
        [ $RETVAL=0 ] && rm -f /var/lock/subsys/alfresco $ALF_HOME/alfresco.pid
    fi
}

status() {
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
    if [ $SHUTDOWN_PORT -eq 0 ]; then
        echo "Alfresco stopped"
    else
        echo "Alfresco running"
    fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  status)
        status
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL
